################################
## Airflow Webserver ServiceAccount
#################################
{{- if .Values.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-webserver
  annotations:
    {{- if .Values.webserver.serviceAccount.annotations }}
    {{- toYaml .Values.webserver.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}